Config.VehicleConfigVersion = '1.2.0'

-- Company garage vehicles and contractor fleet vehicles
Config.JobVehicles = {
    van = {
        {
            label = 'DECLASSE Burrito',
            minRank = 1,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'burrito2',
            photo = '../images/photos/vehicles/burrito2.webp',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                [1] = true,
                [2] = true,
            },
        },
        {
            label = 'BRAVADO Rumpo',
            minRank = 1,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'rumpo',
            photo = '../images/photos/vehicles/rumpo.webp',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = false,
                -- [3] = false,
            },
        },
        {
            label = 'VAPID Speedo',
            minRank = 1,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'speedo',
            photo = '../images/photos/vehicles/speedo.webp',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = false,
                -- [4] = false,
            },
        }, 
        -- {
        --     label = 'BENEFACTOR Runner',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'runner',
        --     photo = '../images/photos/vehicles/runner.webp',
        --     platePrefix = 'LSV',
        --     livery = 3,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        -- {
        --     label = 'BENEFACTOR Imperial',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'imperial',
        --     photo = '../images/photos/vehicles/imperial.webp',
        --     platePrefix = 'LSV',
        --     livery = 3,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        -- {
        --     label = 'BRUTE Navarra',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'navarra',
        --     photo = '../images/photos/vehicles/navarra.webp',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        {
            label = 'BRUTE Pony',
            minRank = 1,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'pony',
            photo = '../images/photos/vehicles/pony.webp',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = false,
                -- [4] = false,
            },
        }, 
        {
            label = 'BRUTE Pony',
            minRank = 1,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'pony2',
            photo = '../images/photos/vehicles/pony2.webp',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = false,
                -- [4] = false,
            },
        }, 
        -- {
        --     label = 'VAPID Steed',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'steed2',
        --     photo = '../images/photos/vehicles/steed2.webp',
        --     platePrefix = 'LSV',
        --     livery = 12,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        -- {
        --     label = 'VAPID Steed',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'steed3',
        --     photo = '../images/photos/vehicles/steed3.webp',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        -- {
        --     label = 'DECLASSE Burrito',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'vburrito1',
        --     photo = '../images/photos/vehicles/vburrito1.webp',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        -- {
        --     label = 'DECLASSE Burrito',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'vburrito2',
        --     photo = '../images/photos/vehicles/vburrito2.webp',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        {
            label = 'BRAVADO Rumpo Priority',
            minRank = 2,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'rumpo2',
            photo = '../images/photos/vehicles/rumpo2.webp',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
            },
        },      
        {
            label = 'VAPID Speedo Priority',
            minRank = 2,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'speedo4',
            photo = '../images/photos/vehicles/speedo4.webp',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = true,
            },
        },
        {
            label = 'VAPID Speedo Priority 2',
            minRank = 2,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'speedo5',
            photo = '../images/photos/vehicles/speedo5.webp',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = true,
            },
        },
        -- {
        --     label = 'VAPID Speedo Express',
        --     minRank = 2,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'nspeedo',
        --     photo = '../images/photos/vehicles/nspeedo.webp',
        --     platePrefix = 'LSV',
        --     livery = 3,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = true,
        --     },
        -- },
        -- {
        --     label = 'BENEFACTOR Jogger Cargo 1',
        --     minRank = 2,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'onx_tfjoggercs1',
        --     photo = '../images/photos/vehicles/onx_tfjoggercs1.webp',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = true,
        --     },
        -- },
        -- {
        --     label = 'BENEFACTOR Jogger Cargo 2',
        --     minRank = 2,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'onx_tfjoggercs2',
        --     photo = '../images/photos/vehicles/onx_tfjoggercs2.webp',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = true,
        --     },
        -- },
        -- {
        --     label = 'BENEFACTOR Jogger Cargo Ex 1',
        --     minRank = 2,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'onx_tfjoggercl1',
        --     photo = '../images/photos/vehicles/onx_tfjoggercl1.webp',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = true,
        --     },
        -- },
        -- {
        --     label = 'BENEFACTOR Jogger Cargo Ex 2',
        --     minRank = 2,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'onx_tfjoggercl2',
        --     photo = '../images/photos/vehicles/onx_tfjoggercl2.webp',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = true,
        --     },
        -- },
        -- {
        --     label = 'Burrito Priority Van',
        --     minRank = 2,
        --     model = 'burrito3',
        --     photo = '../images/photos/vehicles/burrito3.webp',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = true,
        --         [2] = true,
        --     },
        -- },
    },

    boxtruck = {
        {
            label = 'MAIBATSU Mule',
            minRank = 3,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'mule2',
            photo = '../images/photos/vehicles/mule2.webp',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = true,
                [6] = false,
                [7] = false,
            },
        },
        -- {
        --     label = 'MAIBATSU Mule',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'nmule',
        --     photo = '../images/photos/vehicles/nmule.webp',
        --     platePrefix = 'LSB',
        --     livery = 21,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = false,
        --         -- [2] = false,
        --         -- [3] = false,
        --         -- [4] = false,
        --         -- [5] = true,
        --         -- [6] = false,
        --         -- [7] = false,
        --     },
        -- },
        -- {
        --     label = 'BRUTE Boxboy',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'gbboxboy',
        --     photo = '../images/photos/vehicles/gbboxboy.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = false,
        --         [3] = false,
        --         [4] = false,
        --         [5] = true,
        --         [6] = false,
        --         [7] = false,
        --     },
        -- },
        {
            label = 'VAPID Benson',
            minRank = 3,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'benson',
            photo = '../images/photos/vehicles/benson.webp',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = true,
                [7] = false,
                [8] = false,
                [9] = false,
                [10] = false,
                [11] = false,
                [12] = false,
            },
        },
        {
            label = 'MTL Pounder',
            minRank = 3,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'pounder',
            photo = '../images/photos/vehicles/pounder.webp',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                [1] = false,
                [2] = true,
            },
        },
        -- {
        --     label = 'VAPID Yankee',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'vyankee2',
        --     photo = '../images/photos/vehicles/vyankee2.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'VAPID Yankee',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'vyankee1',
        --     photo = '../images/photos/vehicles/vyankee1.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'BRAVADO Rumpo Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'vrumpo2',
        --     photo = '../images/photos/vehicles/vrumpo2.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'VAPID Speedo Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'vspeedo1',
        --     photo = '../images/photos/vehicles/vspeedo1.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'VAPID Steed Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'steed',
        --     photo = '../images/photos/vehicles/steed.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Voyager Box SA',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'gbvoyagerb',
        --     photo = '../images/photos/vehicles/gbvoyagerb.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Voyager Box DA',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'gbvoyagerb2',
        --     photo = '../images/photos/vehicles/gbvoyagerb2.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'VAPID Sandking Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'onx_boxking',
        --     photo = '../images/photos/vehicles/onx_boxking.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = false,
        --     },
        -- },
        -- {
        --     label = 'BRAVADO Bison Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'onx_tfboxson',
        --     photo = '../images/photos/vehicles/onx_tfboxson.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = false,
        --     },
        -- },
        -- {
        --     label = 'VAPID Sandstorm Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'onx_tfboxstorm',
        --     photo = '../images/photos/vehicles/onx_tfboxstorm.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = false,
        --     },
        -- },
        {
            label = 'MAIBATSU Mule Priority',
            minRank = 4,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'mule4',
            photo = '../images/photos/vehicles/mule4.webp',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = true,
            },
        },
        {
            label = 'VAPID Benson Priority',
            minRank = 4,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'benson2',
            photo = '../images/photos/vehicles/benson2.webp',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = false,
            },
        },
        -- {
        --     label = 'VAPID Benson',
        --     minRank = 4,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'vbenson1',
        --     photo = '../images/photos/vehicles/vbenson1.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = false,
        --     },
        -- },
        -- {
        --     label = 'MTL Biff',
        --     minRank = 4,
        --     model = 'vbiff1',
        --     photo = '../images/photos/vehicles/vbiff1.webp',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = false,
        --     },
        -- },
        {
            label = 'MTL Pounder Priority',
            minRank = 4,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'pounder2',
            photo = '../images/photos/vehicles/pounder2.webp',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = true,
            },
        },
    },

    trailer = {
        {
            label = 'JOBUILT Hauler',
            minRank = 4,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'hauler',
            photo = '../images/photos/vehicles/hauler.webp',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                [1] = false,
            },
        },
        {
            label = 'JOBUILT Hauler 270',
            minRank = 4,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'hauler3',
            photo = '../images/photos/vehicles/hauler3.webp',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                [1] = false,
            },
        },
        -- {
        --     label = 'MTL Voyager SA',
        --     minRank = 4,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'gbvoyager',
        --     photo = '../images/photos/vehicles/gbvoyager.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         [1] = false,
        --     },
        -- },
        -- {
        --     label = 'MTL Voyager DA',
        --     minRank = 4,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'gbvoyager2',
        --     photo = '../images/photos/vehicles/gbvoyager2.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         [1] = false,
        --     },
        -- },
        {
            label = 'JOBUILT Phantom',
            minRank = 4,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'phantom',
            photo = '../images/photos/vehicles/phantom.webp',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                [1] = true,
                [2] = false,
                [5] = false,
                [6] = true,
            },
        },
        {
            label = 'MTL Packer',
            minRank = 4,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'packer',
            photo = '../images/photos/vehicles/packer.webp',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                [1] = false,
            },
        },
        {
            label = 'JOBUILT Hauler Priority',
            minRank = 5,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'hauler2',
            photo = '../images/photos/vehicles/hauler2.webp',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                -- [1] = true,
                -- [2] = true,
            },
        },
        {
            label = 'JOBUILT Phantom Priority',
            minRank = 5,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'phantom3',
            photo = '../images/photos/vehicles/phantom3.webp',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                -- [1] = true,
                -- [2] = true,
            },
        },
        {
            label = 'HVY Barracks',
            minRank = 5,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'barracks2',
            photo = '../images/photos/vehicles/barracks2.webp',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                -- [1] = true,
            },
        },
        -- {
        --     label = 'VAPID Tanker',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'aerocab',
        --     photo = '../images/photos/vehicles/aerocab.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'HVY Linerunner',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'linerunner',
        --     photo = '../images/photos/vehicles/linerunner.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'BRUTE Roadkiller',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vroadkiller1',
        --     photo = '../images/photos/vehicles/vroadkiller1.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'JOBUILT Phantom',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vphantom1',
        --     photo = '../images/photos/vehicles/vphantom1.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'JOBUILT Juggernaut',
        --     minRank = 5,
        --     model = 'vjuggernaut1',
        --     photo = '../images/photos/vehicles/vjuggernaut1.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Packer',
        --     minRank = 5,
        --     model = 'vpacker1',
        --     photo = '../images/photos/vehicles/vpacker1.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'JOBUILT Longpath',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vlongpath1',
        --     photo = '../images/photos/vehicles/vlongpath1.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'JOBUILT Longpath T1000',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'longpath',
        --     photo = '../images/photos/vehicles/longpath.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- -- {
        -- --     label = 'JOBUILT Hauler',
        -- --     minRank = 5,
        -- --     model = 'vhauler1',
        -- --     photo = '../images/photos/vehicles/vhauler1.webp',
        -- --     platePrefix = 'LST',
        -- --     truckLivery = 0,
        -- --     fuel = 100,
        -- --     truckExtras = {
        -- --         -- [1] = true,
        -- --     },
        -- -- },
        -- {
        --     label = 'MTL Cerberus',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vcerberus1',
        --     photo = '../images/photos/vehicles/vcerberus1.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Cerberus',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vcerberus2',
        --     photo = '../images/photos/vehicles/vcerberus2.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Cerberus',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vcerberus3',
        --     photo = '../images/photos/vehicles/vcerberus3.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Cerberus',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vcerberus4',
        --     photo = '../images/photos/vehicles/vcerberus4.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Cerberus',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vcerberus5',
        --     photo = '../images/photos/vehicles/vcerberus5.webp',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
    },

}

Config.ContractorVehicleDefaults = {
    van = { enabled = true, base = 85000, minRank = 5 },
    boxtruck = { enabled = true, base = 165000, minRank = 5 },
    trailer = { enabled = true, base = 260000, minRank = 5 },
}

-- Individual vehicle tables can override these defaults with:
-- contractor = { enabled = true, price = 95000, minRank = 5 }
local function ApplyContractorVehicleDefaults()
    for vehicleType, defaults in pairs(Config.ContractorVehicleDefaults) do
        for index, vehicle in ipairs(Config.JobVehicles[vehicleType] or {}) do
            vehicle.contractor = vehicle.contractor or {}

            if vehicle.contractor.enabled == nil then
                vehicle.contractor.enabled = defaults.enabled ~= false
            end

            if vehicle.contractor.price == nil then
                local base = tonumber(defaults.base) or 0
                vehicle.contractor.price = math.floor(base)
            end

            if vehicle.contractor.minRank == nil then
                vehicle.contractor.minRank = tonumber(defaults.minRank) or 5
            end
        end
    end
end

ApplyContractorVehicleDefaults()

