Config.VehicleConfigVersion = '1.0.0'

-- Company garage vehicles and contractor fleet vehicles
Config.JobVehicles = {
    van = {
        {
            label = 'DECLASSE Burrito',
            minRank = 1,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'burrito2',
            photo = 'https://r2.fivemanage.com/image/wo3fcfTiPGvd.png',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                [1] = true,
                [2] = true,
            },
        },
        {
            label = 'BRAVADO Rumpo',
            minRank = 1,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'rumpo',
            photo = 'https://r2.fivemanage.com/image/gjFU3ZFAPwUV.png',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = false,
                -- [3] = false,
            },
        },
        {
            label = 'VAPID Speedo',
            minRank = 1,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'speedo',
            photo = 'https://r2.fivemanage.com/image/9t2hULSCPUDz.png',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = false,
                -- [4] = false,
            },
        }, 
        -- {
        --     label = 'BENEFACTOR Runner',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'runner',
        --     photo = 'https://r2.fivemanage.com/image/s1WV9cSwa1CI.png',
        --     platePrefix = 'LSV',
        --     livery = 3,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        -- {
        --     label = 'BENEFACTOR Imperial',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'imperial',
        --     photo = 'https://r2.fivemanage.com/image/L1bLyf6WtXx1.png',
        --     platePrefix = 'LSV',
        --     livery = 3,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        -- {
        --     label = 'BRUTE Navarra',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'navarra',
        --     photo = 'https://r2.fivemanage.com/image/3Dx37MsavprT.png',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        {
            label = 'BRUTE Pony',
            minRank = 1,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'pony',
            photo = 'https://r2.fivemanage.com/image/5KnJGbWmmZcq.png',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = false,
                -- [4] = false,
            },
        }, 
        {
            label = 'BRUTE Pony',
            minRank = 1,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'pony2',
            photo = 'https://r2.fivemanage.com/image/yTHcFYQDTi5l.png',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = false,
                -- [4] = false,
            },
        }, 
        -- {
        --     label = 'VAPID Steed',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'steed2',
        --     photo = 'https://r2.fivemanage.com/image/yTAYKms5UJzA.png',
        --     platePrefix = 'LSV',
        --     livery = 12,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        -- {
        --     label = 'VAPID Steed',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'steed3',
        --     photo = 'https://r2.fivemanage.com/image/XCwbUBsNTW8v.png',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        -- {
        --     label = 'DECLASSE Burrito',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'vburrito1',
        --     photo = 'https://r2.fivemanage.com/image/65pIW7R2MQTY.png',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        -- {
        --     label = 'DECLASSE Burrito',
        --     minRank = 1,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'vburrito2',
        --     photo = 'https://r2.fivemanage.com/image/iqwqKJSE6aOe.png',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = false,
        --         -- [4] = false,
        --     },
        -- }, 
        {
            label = 'BRAVADO Rumpo Priority',
            minRank = 2,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'rumpo2',
            photo = 'https://r2.fivemanage.com/image/QNQHK4up8AI9.png',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
            },
        },      
        {
            label = 'VAPID Speedo Priority',
            minRank = 2,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'speedo4',
            photo = 'https://r2.fivemanage.com/image/Lh2EaHXTwcBU.png',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = true,
            },
        },
        {
            label = 'VAPID Speedo Priority 2',
            minRank = 2,
            contractor = { enabled = true, price = 85000, minRank = 5 },
            model = 'speedo5',
            photo = 'https://r2.fivemanage.com/image/Lh2EaHXTwcBU.png',
            platePrefix = 'LSV',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = true,
            },
        },
        -- {
        --     label = 'VAPID Speedo Express',
        --     minRank = 2,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'nspeedo',
        --     photo = 'https://r2.fivemanage.com/image/0RGHY83X8wN5.png',
        --     platePrefix = 'LSV',
        --     livery = 3,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = true,
        --     },
        -- },
        -- {
        --     label = 'BENEFACTOR Jogger Cargo 1',
        --     minRank = 2,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'onx_tfjoggercs1',
        --     photo = 'https://r2.fivemanage.com/image/ZrciFqEICRLy.png',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = true,
        --     },
        -- },
        -- {
        --     label = 'BENEFACTOR Jogger Cargo 2',
        --     minRank = 2,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'onx_tfjoggercs2',
        --     photo = 'https://r2.fivemanage.com/image/ZrciFqEICRLy.png',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = true,
        --     },
        -- },
        -- {
        --     label = 'BENEFACTOR Jogger Cargo Ex 1',
        --     minRank = 2,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'onx_tfjoggercl1',
        --     photo = 'https://r2.fivemanage.com/image/DLFPkxNWwxUN.png',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = true,
        --     },
        -- },
        -- {
        --     label = 'BENEFACTOR Jogger Cargo Ex 2',
        --     minRank = 2,
        --     contractor = { enabled = true, price = 85000, minRank = 5 },
        --     model = 'onx_tfjoggercl2',
        --     photo = 'https://r2.fivemanage.com/image/DLFPkxNWwxUN.png',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = true,
        --         -- [3] = true,
        --     },
        -- },
        -- {
        --     label = 'Burrito Priority Van',
        --     minRank = 2,
        --     model = 'burrito3',
        --     photo = 'https://docs.fivem.net/vehicles/burrito3.webp',
        --     platePrefix = 'LSV',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = true,
        --         [2] = true,
        --     },
        -- },
    },

    boxtruck = {
        {
            label = 'MAIBATSU Mule',
            minRank = 3,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'mule2',
            photo = 'https://r2.fivemanage.com/image/ql88eiu03rkS.png',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = true,
                [6] = false,
                [7] = false,
            },
        },
        -- {
        --     label = 'MAIBATSU Mule',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'nmule',
        --     photo = 'https://r2.fivemanage.com/image/U6492YAHrrZj.png',
        --     platePrefix = 'LSB',
        --     livery = 21,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = false,
        --         -- [2] = false,
        --         -- [3] = false,
        --         -- [4] = false,
        --         -- [5] = true,
        --         -- [6] = false,
        --         -- [7] = false,
        --     },
        -- },
        -- {
        --     label = 'BRUTE Boxboy',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'gbboxboy',
        --     photo = 'https://r2.fivemanage.com/image/S7hQXVVs8QFq.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = false,
        --         [3] = false,
        --         [4] = false,
        --         [5] = true,
        --         [6] = false,
        --         [7] = false,
        --     },
        -- },
        {
            label = 'VAPID Benson',
            minRank = 3,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'benson',
            photo = 'https://r2.fivemanage.com/image/rPzYWDkurGe8.png',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                [1] = false,
                [2] = false,
                [3] = false,
                [4] = false,
                [5] = false,
                [6] = true,
                [7] = false,
                [8] = false,
                [9] = false,
                [10] = false,
                [11] = false,
                [12] = false,
            },
        },
        {
            label = 'MTL Pounder',
            minRank = 3,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'pounder',
            photo = 'https://r2.fivemanage.com/image/mFkiGjePKItf.png',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                [1] = false,
                [2] = true,
            },
        },
        -- {
        --     label = 'VAPID Yankee',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'vyankee2',
        --     photo = 'https://r2.fivemanage.com/image/Ejo2AfY5rg1I.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'VAPID Yankee',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'vyankee1',
        --     photo = 'https://r2.fivemanage.com/image/iJX5GvaId3QI.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'BRAVADO Rumpo Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'vrumpo2',
        --     photo = 'https://r2.fivemanage.com/image/FI5Zfz44f8j7.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'VAPID Speedo Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'vspeedo1',
        --     photo = 'https://r2.fivemanage.com/image/rsttdPcoE4fV.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'VAPID Steed Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'steed',
        --     photo = 'https://r2.fivemanage.com/image/U3lj7F2radQw.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Voyager Box SA',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'gbvoyagerb',
        --     photo = 'https://r2.fivemanage.com/image/hgQtvDvccOuH.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Voyager Box DA',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'gbvoyagerb2',
        --     photo = 'https://r2.fivemanage.com/image/1xmLpe7wBPGj.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = true,
        --     },
        -- },
        -- {
        --     label = 'VAPID Sandking Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'onx_boxking',
        --     photo = 'https://r2.fivemanage.com/image/7LBU1sMsa09C.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = false,
        --     },
        -- },
        -- {
        --     label = 'BRAVADO Bison Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'onx_tfboxson',
        --     photo = 'https://r2.fivemanage.com/image/Q41Tm9ik8XOR.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = false,
        --     },
        -- },
        -- {
        --     label = 'VAPID Sandstorm Box',
        --     minRank = 3,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'onx_tfboxstorm',
        --     photo = 'https://r2.fivemanage.com/image/Y1wwMqhvdDTl.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         [1] = false,
        --         [2] = false,
        --     },
        -- },
        {
            label = 'MAIBATSU Mule Priority',
            minRank = 4,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'mule4',
            photo = 'https://r2.fivemanage.com/image/yiaXfhCKSkfc.png',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = true,
            },
        },
        {
            label = 'VAPID Benson Priority',
            minRank = 4,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'benson2',
            photo = 'https://r2.fivemanage.com/image/kshxm4TlwFB7.png',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = false,
            },
        },
        -- {
        --     label = 'VAPID Benson',
        --     minRank = 4,
        --     contractor = { enabled = true, price = 165000, minRank = 5 },
        --     model = 'vbenson1',
        --     photo = 'https://r2.fivemanage.com/image/BMAFpLE3q8zq.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = false,
        --     },
        -- },
        -- {
        --     label = 'MTL Biff',
        --     minRank = 4,
        --     model = 'vbiff1',
        --     photo = 'https://r2.fivemanage.com/image/5gH0waDe4Ht7.png',
        --     platePrefix = 'LSB',
        --     livery = 0,
        --     fuel = 100,
        --     extras = {
        --         -- [1] = true,
        --         -- [2] = false,
        --     },
        -- },
        {
            label = 'MTL Pounder Priority',
            minRank = 4,
            contractor = { enabled = true, price = 165000, minRank = 5 },
            model = 'pounder2',
            photo = 'https://r2.fivemanage.com/image/nRtz0yU2ekhm.png',
            platePrefix = 'LSB',
            livery = 0,
            fuel = 100,
            extras = {
                -- [1] = true,
                -- [2] = true,
                -- [3] = true,
            },
        },
    },

    trailer = {
        {
            label = 'JOBUILT Hauler',
            minRank = 4,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'hauler',
            photo = 'https://r2.fivemanage.com/image/2jxKuUWclvYe.png',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                [1] = false,
            },
        },
        {
            label = 'JOBUILT Hauler 270',
            minRank = 4,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'hauler3',
            photo = 'https://r2.fivemanage.com/image/rcupfD1acRNL.png',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                [1] = false,
            },
        },
        -- {
        --     label = 'MTL Voyager SA',
        --     minRank = 4,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'gbvoyager',
        --     photo = 'https://r2.fivemanage.com/image/q393omJCCyvF.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         [1] = false,
        --     },
        -- },
        -- {
        --     label = 'MTL Voyager DA',
        --     minRank = 4,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'gbvoyager2',
        --     photo = 'https://r2.fivemanage.com/image/ZMipzAlwilky.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         [1] = false,
        --     },
        -- },
        {
            label = 'JOBUILT Phantom',
            minRank = 4,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'phantom',
            photo = 'https://r2.fivemanage.com/image/gwScvkLSG98L.png',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                [1] = true,
                [2] = false,
                [5] = false,
                [6] = true,
            },
        },
        {
            label = 'MTL Packer',
            minRank = 4,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'packer',
            photo = 'https://r2.fivemanage.com/image/0TDO4hl8JYry.png',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                [1] = false,
            },
        },
        {
            label = 'JOBUILT Hauler Priority',
            minRank = 5,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'hauler2',
            photo = 'https://r2.fivemanage.com/image/8pjds4sEDBZP.png',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                -- [1] = true,
                -- [2] = true,
            },
        },
        {
            label = 'JOBUILT Phantom Priority',
            minRank = 5,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'phantom3',
            photo = 'https://r2.fivemanage.com/image/OAzEyB85lm5A.png',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                -- [1] = true,
                -- [2] = true,
            },
        },
        {
            label = 'HVY Barracks',
            minRank = 5,
            contractor = { enabled = true, price = 260000, minRank = 5 },
            model = 'barracks2',
            photo = 'https://r2.fivemanage.com/image/0SPB34SMpKpK.png',
            platePrefix = 'LST',
            truckLivery = 0,
            fuel = 100,
            truckExtras = {
                -- [1] = true,
            },
        },
        -- {
        --     label = 'VAPID Tanker',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'aerocab',
        --     photo = 'https://r2.fivemanage.com/image/jDId4Hawdkah.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'HVY Linerunner',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'linerunner',
        --     photo = 'https://r2.fivemanage.com/image/bZL1w8JSjfEV.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'BRUTE Roadkiller',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vroadkiller1',
        --     photo = 'https://r2.fivemanage.com/image/byOV5UENgZWo.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'JOBUILT Phantom',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vphantom1',
        --     photo = 'https://r2.fivemanage.com/image/Wlyzhy2GFg5P.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'JOBUILT Juggernaut',
        --     minRank = 5,
        --     model = 'vjuggernaut1',
        --     photo = 'https://r2.fivemanage.com/image/6j34vHJYH7a6.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Packer',
        --     minRank = 5,
        --     model = 'vpacker1',
        --     photo = 'https://r2.fivemanage.com/image/lfItRXVH9tDw.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'JOBUILT Longpath',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vlongpath1',
        --     photo = 'https://r2.fivemanage.com/image/lloAeSdQihem.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'JOBUILT Longpath T1000',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'longpath',
        --     photo = 'https://r2.fivemanage.com/image/lloAeSdQihem.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- -- {
        -- --     label = 'JOBUILT Hauler',
        -- --     minRank = 5,
        -- --     model = 'vhauler1',
        -- --     photo = 'https://r2.fivemanage.com/image/U1CoVvYRFDUR.png',
        -- --     platePrefix = 'LST',
        -- --     truckLivery = 0,
        -- --     fuel = 100,
        -- --     truckExtras = {
        -- --         -- [1] = true,
        -- --     },
        -- -- },
        -- {
        --     label = 'MTL Cerberus',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vcerberus1',
        --     photo = 'https://r2.fivemanage.com/image/xGduj03AYob6.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Cerberus',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vcerberus2',
        --     photo = 'https://r2.fivemanage.com/image/eCEP3DPMpjWN.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Cerberus',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vcerberus3',
        --     photo = 'https://r2.fivemanage.com/image/SKYfXvV7oHm8.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Cerberus',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vcerberus4',
        --     photo = 'https://r2.fivemanage.com/image/knNAuVDAHqKP.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
        -- {
        --     label = 'MTL Cerberus',
        --     minRank = 5,
        --     contractor = { enabled = true, price = 260000, minRank = 5 },
        --     model = 'vcerberus5',
        --     photo = 'https://r2.fivemanage.com/image/Lv7UBqcCFpuC.png',
        --     platePrefix = 'LST',
        --     truckLivery = 0,
        --     fuel = 100,
        --     truckExtras = {
        --         -- [1] = true,
        --     },
        -- },
    },

}

Config.ContractorVehicleDefaults = {
    van = { enabled = true, base = 85000, minRank = 5 },
    boxtruck = { enabled = true, base = 165000, minRank = 5 },
    trailer = { enabled = true, base = 260000, minRank = 5 },
}

-- Individual vehicle tables can override these defaults with:
-- contractor = { enabled = true, price = 95000, minRank = 5 }
local function ApplyContractorVehicleDefaults()
    for vehicleType, defaults in pairs(Config.ContractorVehicleDefaults) do
        for index, vehicle in ipairs(Config.JobVehicles[vehicleType] or {}) do
            vehicle.contractor = vehicle.contractor or {}

            if vehicle.contractor.enabled == nil then
                vehicle.contractor.enabled = defaults.enabled ~= false
            end

            if vehicle.contractor.price == nil then
                local base = tonumber(defaults.base) or 0
                vehicle.contractor.price = math.floor(base)
            end

            if vehicle.contractor.minRank == nil then
                vehicle.contractor.minRank = tonumber(defaults.minRank) or 5
            end
        end
    end
end

ApplyContractorVehicleDefaults()

